### ISSUE TITLE
bug:微信code登录失败

### ISSUE THREAD

**Issue by Dcell** [Code-Dogs/StarGithubPlatform#11]
协议：http://c2.orzjj.com:8762/doc.html#/2.X%E7%89%88%E6%9C%AC/%E5%BE%AE%E4%BF%A1%E7%9B%B8%E5%85%B3%E6%8E%A5%E5%8F%A3/createAuthenticationTokenByCodeUsingPOST
登录失败，返回500

**Comment by Dcell** [comment]
@bivana

**Comment by bivana** [comment]
response only have openind and sessiion key,it's diffrenet with the weixin offecial document
![image](https://user-images.githubusercontent.com/16237631/102003983-3b316f80-3d47-11eb-9a6a-eba2202334da.png)
![image](https://user-images.githubusercontent.com/16237631/102003987-42587d80-3d47-11eb-9427-88a4a58713ac.png)
now it solved

**Comment by Dcell** [comment]
Test Pass
